cmake_minimum_required(VERSION 3.5)
project(kinlib)

# Set CXX Standard for the project
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

#set(USE_PYTHON_BINDINGS ON) # Uncomment this to use python bindings

include(GNUInstallDirs)

set(KINLIB_RESOURCES_DIR "${CMAKE_CURRENT_LIST_DIR}/files/")
configure_file("include/${PROJECT_NAME}/${PROJECT_NAME}_resources.h.in" "${CMAKE_BINARY_DIR}/include/${PROJECT_NAME}/${PROJECT_NAME}_resources.h")

# Control where libraries and executables are placed during the build
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR}")

# find_package(Eigen3 REQUIRED)
#
# if(NOT EIGEN3_INCLUDE_DIRS)
#   set(EIGEN3_INCLUDE_DIRS ${EIGEN3_INCLUDE_DIR})
# endif()
#
# #find_package(Boost REQUIRED system filesystem)
#
# include_directories(
#   include
#   ${EIGEN3_INCLUDE_DIRS}
# )

include_directories(
  include
  ${CMAKE_CURRENT_SOURCE_DIR}/external/eigen
)

# ./bin/null_space_baxter
# mkdir build
# cd build
# cmake ..
# make

add_library(${PROJECT_NAME}
  src/DualQuat.cpp
  src/manipulator.cpp
  src/kinlib_kinematics.cpp
  src/motion_planning.cpp
  src/nullSpace_kinematics.cpp
  src/robot_parameter.cpp
)

if(USE_PYTHON_BINDINGS)
  set(PYBIND11_FINDPYTHON ON)
  find_package(pybind11 CONFIG REQUIRED)
  pybind11_add_module(kinlib_cpp src/python_bindings.cpp)
  target_link_libraries(kinlib_cpp PRIVATE ${PROJECT_NAME})
endif()

target_include_directories(${PROJECT_NAME} PUBLIC
	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
	$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>
	$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

install(TARGETS ${PROJECT_NAME}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

install(DIRECTORY include/
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  FILES_MATCHING PATTERN "*.h")

install(FILES ${PROJECT_BINARY_DIR}/include/${PROJECT_NAME}/${PROJECT_NAME}_resources.h
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME})

# add_executable(kinlib_example src/example.cpp)
# target_include_directories(kinlib_example PUBLIC
# 	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
# 	$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>
# 	$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
# target_link_libraries(kinlib_example ${PROJECT_NAME})

add_executable(kinlib_projectaria src/projectaria.cpp)
target_include_directories(kinlib_projectaria PUBLIC
	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
	$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>
	$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(kinlib_projectaria ${PROJECT_NAME})


add_executable(null_space_softlimit src/null_space_softlimit.cpp)
target_include_directories(null_space_softlimit PUBLIC
	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
	$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>
	$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(null_space_softlimit ${PROJECT_NAME})


add_executable(null_space_baxter src/null_space_baxter.cpp)
target_include_directories(null_space_baxter PUBLIC
	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
	$<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>
	$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(null_space_baxter ${PROJECT_NAME})

