# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mgoldhaber2027/Desktop/kinlib-aria

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mgoldhaber2027/Desktop/kinlib-aria

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mgoldhaber2027/Desktop/kinlib-aria/CMakeFiles /Users/mgoldhaber2027/Desktop/kinlib-aria//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mgoldhaber2027/Desktop/kinlib-aria/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kinlib

# Build rule for target.
kinlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kinlib
.PHONY : kinlib

# fast build rule for target.
kinlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/build
.PHONY : kinlib/fast

#=============================================================================
# Target rules for targets named kinlib_projectaria

# Build rule for target.
kinlib_projectaria: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kinlib_projectaria
.PHONY : kinlib_projectaria

# fast build rule for target.
kinlib_projectaria/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib_projectaria.dir/build.make CMakeFiles/kinlib_projectaria.dir/build
.PHONY : kinlib_projectaria/fast

#=============================================================================
# Target rules for targets named null_space_softlimit

# Build rule for target.
null_space_softlimit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 null_space_softlimit
.PHONY : null_space_softlimit

# fast build rule for target.
null_space_softlimit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_softlimit.dir/build.make CMakeFiles/null_space_softlimit.dir/build
.PHONY : null_space_softlimit/fast

#=============================================================================
# Target rules for targets named null_space_baxter

# Build rule for target.
null_space_baxter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 null_space_baxter
.PHONY : null_space_baxter

# fast build rule for target.
null_space_baxter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_baxter.dir/build.make CMakeFiles/null_space_baxter.dir/build
.PHONY : null_space_baxter/fast

src/DualQuat.o: src/DualQuat.cpp.o
.PHONY : src/DualQuat.o

# target to build an object file
src/DualQuat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/DualQuat.cpp.o
.PHONY : src/DualQuat.cpp.o

src/DualQuat.i: src/DualQuat.cpp.i
.PHONY : src/DualQuat.i

# target to preprocess a source file
src/DualQuat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/DualQuat.cpp.i
.PHONY : src/DualQuat.cpp.i

src/DualQuat.s: src/DualQuat.cpp.s
.PHONY : src/DualQuat.s

# target to generate assembly for a file
src/DualQuat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/DualQuat.cpp.s
.PHONY : src/DualQuat.cpp.s

src/kinlib_kinematics.o: src/kinlib_kinematics.cpp.o
.PHONY : src/kinlib_kinematics.o

# target to build an object file
src/kinlib_kinematics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/kinlib_kinematics.cpp.o
.PHONY : src/kinlib_kinematics.cpp.o

src/kinlib_kinematics.i: src/kinlib_kinematics.cpp.i
.PHONY : src/kinlib_kinematics.i

# target to preprocess a source file
src/kinlib_kinematics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/kinlib_kinematics.cpp.i
.PHONY : src/kinlib_kinematics.cpp.i

src/kinlib_kinematics.s: src/kinlib_kinematics.cpp.s
.PHONY : src/kinlib_kinematics.s

# target to generate assembly for a file
src/kinlib_kinematics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/kinlib_kinematics.cpp.s
.PHONY : src/kinlib_kinematics.cpp.s

src/manipulator.o: src/manipulator.cpp.o
.PHONY : src/manipulator.o

# target to build an object file
src/manipulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/manipulator.cpp.o
.PHONY : src/manipulator.cpp.o

src/manipulator.i: src/manipulator.cpp.i
.PHONY : src/manipulator.i

# target to preprocess a source file
src/manipulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/manipulator.cpp.i
.PHONY : src/manipulator.cpp.i

src/manipulator.s: src/manipulator.cpp.s
.PHONY : src/manipulator.s

# target to generate assembly for a file
src/manipulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/manipulator.cpp.s
.PHONY : src/manipulator.cpp.s

src/motion_planning.o: src/motion_planning.cpp.o
.PHONY : src/motion_planning.o

# target to build an object file
src/motion_planning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/motion_planning.cpp.o
.PHONY : src/motion_planning.cpp.o

src/motion_planning.i: src/motion_planning.cpp.i
.PHONY : src/motion_planning.i

# target to preprocess a source file
src/motion_planning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/motion_planning.cpp.i
.PHONY : src/motion_planning.cpp.i

src/motion_planning.s: src/motion_planning.cpp.s
.PHONY : src/motion_planning.s

# target to generate assembly for a file
src/motion_planning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/motion_planning.cpp.s
.PHONY : src/motion_planning.cpp.s

src/nullSpace_kinematics.o: src/nullSpace_kinematics.cpp.o
.PHONY : src/nullSpace_kinematics.o

# target to build an object file
src/nullSpace_kinematics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/nullSpace_kinematics.cpp.o
.PHONY : src/nullSpace_kinematics.cpp.o

src/nullSpace_kinematics.i: src/nullSpace_kinematics.cpp.i
.PHONY : src/nullSpace_kinematics.i

# target to preprocess a source file
src/nullSpace_kinematics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/nullSpace_kinematics.cpp.i
.PHONY : src/nullSpace_kinematics.cpp.i

src/nullSpace_kinematics.s: src/nullSpace_kinematics.cpp.s
.PHONY : src/nullSpace_kinematics.s

# target to generate assembly for a file
src/nullSpace_kinematics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/nullSpace_kinematics.cpp.s
.PHONY : src/nullSpace_kinematics.cpp.s

src/null_space_baxter.o: src/null_space_baxter.cpp.o
.PHONY : src/null_space_baxter.o

# target to build an object file
src/null_space_baxter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_baxter.dir/build.make CMakeFiles/null_space_baxter.dir/src/null_space_baxter.cpp.o
.PHONY : src/null_space_baxter.cpp.o

src/null_space_baxter.i: src/null_space_baxter.cpp.i
.PHONY : src/null_space_baxter.i

# target to preprocess a source file
src/null_space_baxter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_baxter.dir/build.make CMakeFiles/null_space_baxter.dir/src/null_space_baxter.cpp.i
.PHONY : src/null_space_baxter.cpp.i

src/null_space_baxter.s: src/null_space_baxter.cpp.s
.PHONY : src/null_space_baxter.s

# target to generate assembly for a file
src/null_space_baxter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_baxter.dir/build.make CMakeFiles/null_space_baxter.dir/src/null_space_baxter.cpp.s
.PHONY : src/null_space_baxter.cpp.s

src/null_space_softlimit.o: src/null_space_softlimit.cpp.o
.PHONY : src/null_space_softlimit.o

# target to build an object file
src/null_space_softlimit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_softlimit.dir/build.make CMakeFiles/null_space_softlimit.dir/src/null_space_softlimit.cpp.o
.PHONY : src/null_space_softlimit.cpp.o

src/null_space_softlimit.i: src/null_space_softlimit.cpp.i
.PHONY : src/null_space_softlimit.i

# target to preprocess a source file
src/null_space_softlimit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_softlimit.dir/build.make CMakeFiles/null_space_softlimit.dir/src/null_space_softlimit.cpp.i
.PHONY : src/null_space_softlimit.cpp.i

src/null_space_softlimit.s: src/null_space_softlimit.cpp.s
.PHONY : src/null_space_softlimit.s

# target to generate assembly for a file
src/null_space_softlimit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/null_space_softlimit.dir/build.make CMakeFiles/null_space_softlimit.dir/src/null_space_softlimit.cpp.s
.PHONY : src/null_space_softlimit.cpp.s

src/projectaria.o: src/projectaria.cpp.o
.PHONY : src/projectaria.o

# target to build an object file
src/projectaria.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib_projectaria.dir/build.make CMakeFiles/kinlib_projectaria.dir/src/projectaria.cpp.o
.PHONY : src/projectaria.cpp.o

src/projectaria.i: src/projectaria.cpp.i
.PHONY : src/projectaria.i

# target to preprocess a source file
src/projectaria.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib_projectaria.dir/build.make CMakeFiles/kinlib_projectaria.dir/src/projectaria.cpp.i
.PHONY : src/projectaria.cpp.i

src/projectaria.s: src/projectaria.cpp.s
.PHONY : src/projectaria.s

# target to generate assembly for a file
src/projectaria.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib_projectaria.dir/build.make CMakeFiles/kinlib_projectaria.dir/src/projectaria.cpp.s
.PHONY : src/projectaria.cpp.s

src/robot_parameter.o: src/robot_parameter.cpp.o
.PHONY : src/robot_parameter.o

# target to build an object file
src/robot_parameter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/robot_parameter.cpp.o
.PHONY : src/robot_parameter.cpp.o

src/robot_parameter.i: src/robot_parameter.cpp.i
.PHONY : src/robot_parameter.i

# target to preprocess a source file
src/robot_parameter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/robot_parameter.cpp.i
.PHONY : src/robot_parameter.cpp.i

src/robot_parameter.s: src/robot_parameter.cpp.s
.PHONY : src/robot_parameter.s

# target to generate assembly for a file
src/robot_parameter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kinlib.dir/build.make CMakeFiles/kinlib.dir/src/robot_parameter.cpp.s
.PHONY : src/robot_parameter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... kinlib"
	@echo "... kinlib_projectaria"
	@echo "... null_space_baxter"
	@echo "... null_space_softlimit"
	@echo "... src/DualQuat.o"
	@echo "... src/DualQuat.i"
	@echo "... src/DualQuat.s"
	@echo "... src/kinlib_kinematics.o"
	@echo "... src/kinlib_kinematics.i"
	@echo "... src/kinlib_kinematics.s"
	@echo "... src/manipulator.o"
	@echo "... src/manipulator.i"
	@echo "... src/manipulator.s"
	@echo "... src/motion_planning.o"
	@echo "... src/motion_planning.i"
	@echo "... src/motion_planning.s"
	@echo "... src/nullSpace_kinematics.o"
	@echo "... src/nullSpace_kinematics.i"
	@echo "... src/nullSpace_kinematics.s"
	@echo "... src/null_space_baxter.o"
	@echo "... src/null_space_baxter.i"
	@echo "... src/null_space_baxter.s"
	@echo "... src/null_space_softlimit.o"
	@echo "... src/null_space_softlimit.i"
	@echo "... src/null_space_softlimit.s"
	@echo "... src/projectaria.o"
	@echo "... src/projectaria.i"
	@echo "... src/projectaria.s"
	@echo "... src/robot_parameter.o"
	@echo "... src/robot_parameter.i"
	@echo "... src/robot_parameter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

